export const worksData = [
  {
    cardHeading: "Supergirl",
    cardSubHeading: "2016 - 2021",
    cardLink: "https://www.cwtv.com/shows/supergirl/?campaign=google_kp_watch",
    cardImage: "images/Supergirl.jpg",
    imageAltText: "Lena Luthor",
  },
  {
    cardHeading: "Crisis on Infinite Earths",
    cardSubHeading: "2020",
    cardLink: "https://www.cwtv.com/shows/supergirl/?campaign=google_kp_watch",
    cardImage: "images/Crisis.jpg",
    imageAltText: "Lena Luthor",
  },
  {
    cardHeading: "Secret Bridesmaids' Business ",
    cardSubHeading: "Since 2019",
    cardLink: "https://www.cwtv.com/shows/supergirl/?campaign=google_kp_watch",
    cardImage: "images/Secret.jpg",
    imageAltText: "Saskia De Merindol",
  },
  {
    cardHeading: "Buttons, A Christmas Tale",
    cardSubHeading: "2018",
    cardLink: "https://www.imdb.com/title/tt9248032/",
    cardImage: "images/Buttons.jpg",
    imageAltText: "Mrs. Wentworth",
  },
  {
    cardHeading: "King Arthur: Legend of the Sword",
    cardSubHeading: "2017",
    cardLink: "https://www.youtube.com/watch?v=M_9wFE4LijI",
    cardImage: "images/King Arthur1.jpg",
    imageAltText: "Elsa",
  },
  {
    cardHeading: "Slasher VR",
    cardSubHeading: "2017",
    cardLink: "https://store.steampowered.com/app/674160/Slasher_VR/",
    cardImage: "images/Slasher VR.png",
    imageAltText: "",
  },
  {
    cardHeading: "Frontier",
    cardSubHeading: "2016-2017",
    cardLink: "https://www.netflix.com/title/80099656",
    cardImage: "images/Frontier1.jpg",
    imageAltText: "Elizabeth Carruthers",
  },
  {
    cardHeading: "Slasher",
    cardSubHeading: "2016",
    cardLink: "https://www.netflix.com/title/80105452",
    cardImage: "images/Slasher.jpg",
    imageAltText: "Sarah Bennett",
  },
  {
    cardHeading: "The Throwaways",
    cardSubHeading: "2015",
    cardLink: "https://www.sonycrackle.com/watch/2582/2494494",
    cardImage: "images/The Throwaways.jpg",
    imageAltText: "Gloria",
  },
  {
    cardHeading: "Jurassic World",
    cardSubHeading: "2015",
    cardLink: "https://www.imdb.com/title/tt0369610/",
    cardImage: "images/Dinoooooo.png",
    imageAltText: "Zara",
  },
  {
    cardHeading: "Leading Lady",
    cardSubHeading: "2014",
    cardLink: "https://www.vudu.com/content/movies/details/Leading-Lady/678472",
    cardImage: "images/Leading Lady.jpg",
    imageAltText: "Jodi Rutherford",
  },
  {
    cardHeading: "Hozier: From Eden",
    cardSubHeading: "2014",
    cardLink: "https://www.youtube.com/watch?v=cI0wUoCLnLk",
    cardImage: "images/Hozier.jpg",
    imageAltText: "",
  },
  
  {
    cardHeading: "Dracula",
    cardSubHeading: "2013 - 2013",
    cardLink: "https://www.nbc.com/dracula",
    cardImage: "images/Dracula.jpg",
    imageAltText: "Lucy Westenra",
  },
  {
    cardHeading: "Dates",
    cardSubHeading: "2013",
    cardLink: "https://www.youtube.com/watch?v=zw2ml2RobUs",
    cardImage: "images/Dates.jpg",
    imageAltText: "Kate",
  },
  {
    cardHeading: "Merlin",
    cardSubHeading: "2008 - 2012",
    cardLink: "https://www.netflix.com/title/70142436",
    cardImage: "images/Merlin.jpg",
    imageAltText: "Morgana",
  },
  {
    cardHeading: "Labyrinth",
    cardSubHeading: "2012",
    cardLink: "https://www.amazon.com/gp/video/detail/B00K81ISGE/ref=atv_dl_rdr",
    cardImage: "images/Labyrinth.jpg",
    imageAltText: "Oriane Congost",
  },
  {
    cardHeading: "Tríd An Stoirm (Into the Storm)",
    cardSubHeading: "2012",
    cardLink: "https://vimeo.com/49308632",
    cardImage: "images/Tríd An Stoirm.jpg",
    imageAltText: "Alice / Banshee",
  },
  {
    cardHeading: "A Princess for Christmas",
    cardSubHeading: "2011",
    cardLink: "https://www.amazon.com/gp/video/detail/B018QD76MW/ref=atv_dl_rdr",
    cardImage: "images/A Princess for Christmas.jpg",
    imageAltText: "Jules Daly",
  },
  {
    cardHeading: "W.E.",
    cardSubHeading: "2011",
    cardLink: "https://www.youtube.com/watch?v=50fjbkkwBI8",
    cardImage: "images/W.E.jpg",
    imageAltText: "Lady Thelma",
  },
  {
    cardHeading: "Children in Need",
    cardSubHeading: "2009 - 2010",
    cardLink: "https://www.imdb.com/title/tt0126739/?ref_=nm_flmg_act_20",
    cardImage: "images/Children.png",
    imageAltText: "Morgana",
  },
  {
    cardHeading: "The Queen",
    cardSubHeading: "2009",
    cardLink: "https://www.imdb.com/title/tt1365539/?ref_=nm_flmg_act_21",
    cardImage: "images/The Queen.jpg",
    imageAltText: "Princess Margaret",
  },
 
  {
    cardHeading: "The Tudors",
    cardSubHeading: "2008",
    cardLink: "https://www.imdb.com/title/tt0758790/",
    cardImage: "images/The Tudors.jpg",
    imageAltText: "Bess",
  },
  {
    cardHeading: "Freakdog (Red Mist)",
    cardSubHeading: "2008",
    cardLink: "https://www.youtube.com/watch?v=dtYcsRGp5tg",
    cardImage: "images/Freakdog.jpg",
    imageAltText: "Harriet",
  },
];
